# Generated by Django 3.1.3 on 2020-11-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20201114_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizzes',
            old_name='quiz_name',
            new_name='quiz_category',
        ),
        migrations.AddField(
            model_name='quizzes',
            name='quiz_difficulty',
            field=models.CharField(default='easy', max_length=100),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='quiz_link',
            field=models.URLField(default='NA'),
        ),
    ]
