# Generated by Django 3.1.3 on 2020-11-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201114_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='quiz_link',
        ),
    ]
