# Generated by Django 3.1.3 on 2020-11-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_quizzes_quiz_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='category_id',
        ),
    ]
