# Generated by Django 3.1.3 on 2020-11-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_quizzes_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='quiz_category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='quiz_difficulty',
            field=models.CharField(blank=True, default='easy', max_length=100, null=True),
        ),
    ]
